config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "instruments#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :instruments do
    collection do
      get :my_instruments
    end
    resources :rentals, only: %i[new create]
  end

  resources :rentals, only: %i[index show edit update destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  belongs_to :user
  has_many :rentals, dependent: :destroy
  has_one_attached :photo
  validates :name, presence: true
  validates :address, presence: true #, length: { minimum: 6 }
  validates :price, presence: true

  include InstrumentConcern
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :instrument
  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :instruments, dependent: :destroy
  has_many :rentals, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :usernamme])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/concerns/instrument_concern.rb
require_relative '../../../config/initializers/array'

module InstrumentConcern
  def booked_dates
    rentals.pluck(:start_date, :end_date)
  end

  def simple_format_booked_dates
    # renvoie un array d'array des dates de debut et de fin
    # de tous les bookings du pokemon mais sous la forme stringifiée : "1991-12-28"
    booked_dates.deep_map(&:to_s)
  end

  def booked_dates_json_objects
    simple_format_booked_dates.map do |dates_arr|
      {
        from: dates_arr.first,
        to: dates_arr.last
      }
    end
  end

  def flatpickr_booked_dates_object
    {
      dateFormat: "Y-m-d",
      disable: booked_dates_json_objects
    }
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @my_instruments = policy_scope(Instrument)
    # @instruments = Instrument.all.where.not(user: current_user)
    # @instruments = Instrument.all
    if params[:query].present?
      @instruments = Instrument.where("name ILIKE ?", "%#{params[:query]}%")
    else
      @instruments = Instrument.all
    end
    @markers = @instruments.geocoded.map do |instrument|
    {
      lat: instrument.latitude,
      lng: instrument.longitude,
      info_window: render_to_string(partial: "info_window", locals: {instrument: instrument}),
      image_url: helpers.asset_url("guitar.png")
    }
    end
  end

  def my_instruments
    @my_instruments = policy_scope(Instrument)
    @rentals = policy_scope(Rental)
    @my_rentals = Rental.where(instrument: @my_instruments)
    authorize @my_instruments
  end

  def show
    @instrument = Instrument.find(params[:id])
    authorize @instrument
    @rental = Rental.new
  end

  def new
    @instrument = Instrument.new
    authorize @instrument
  end

  def create
    @instrument = Instrument.new(instruments_params)
    @instrument.user = current_user
    authorize @instrument
    if @instrument.save
      redirect_to instrument_path(@instrument)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @instrument = Instrument.find(params[:id])
    authorize @instrument
  end

  def update
    @instrument = Instrument.find(params[:id])
    @instrument.update(instruments_params)
    authorize @instrument
    redirect_to instrument_path(@instrument)
  end

  def destroy
    authorize @instrument
    @instrument.destroy
    redirect_to instruments_path, status: :see_other
  end

  private

  def instruments_params
    params.require(:instrument).permit(:name, :description, :address, :price, :photo)
  end

  def set_instrument
    @instrument = Instrument.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_instrument, only: %i[create new]
  before_action :set_rental, only: %i[show edit update show destroy]

  def show
    authorize @rental
  end

  def new
    @rental = Rental.new
    authorize @rental
  end

  def create
    @rental = Rental.new(rental_params)
    authorize @rental
    @rental.instrument = @instrument
    @rental.user = current_user
    if @rental.save
      redirect_to my_instruments_instruments_path
    else
      render 'instruments/show', status: :unprocessable_entity
    end
  end

  def edit
    authorize @rental
  end

  def update
    authorize @rental
    @rental.update(status: params[:rental][:status])
    redirect_to rentals_path
  end

  def index
    @rentals = policy_scope(Rental)
    my_instruments = Instrument.all.where(user: current_user)
    @my_rentals = Rental.where(instrument: my_instruments)
  end

  def destroy
    authorize @rental
    @rental.destroy
    redirect_to my_instruments_instruments_path, status: :see_other
  end

  private

  def rental_params
    params.require(:rental).permit(:start_date, :end_date)
  end

  def set_instrument
    @instrument = Instrument.find(params[:instrument_id])
  end

  def set_rental
    @rental = Rental.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/instruments/_info_window.html.erb
<h2><%= instrument.name %></h2>
<p><%= instrument.address %></p>

app/views/instruments/edit.html.erb
<div class="card-half">
  <h2>Edit a music instrument</h2><br>
  <%= simple_form_for(@instrument) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.submit  class: 'btn-large' %>
  <% end %>
</div>

app/views/instruments/index.html.erb
<div class="banner">
</div>
<div class="grid-center">
  <%= render 'shared/title-center'%>
  <div class="grid">
    <% @instruments.each do |instrument| %>
      <%= link_to instrument_path(instrument) do %>
        <div class="card">
          <% if instrument.photo != nil %>
            <%= cl_image_tag instrument.photo.key, height: 300, width: 400, crop: :fill %>
          <% end %>
          <div class="card-infos">
            <div>
              <h2><%= instrument.name%></h2>
              <div class="text-card">
              <p><%= instrument.description%></p>
              </div><br>
              <h2 class="card-pricing">€<%= instrument.price %></h2>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

  <hr>

  <div style="width: 100%; height: 600px;"
              data-controller="map"
              data-map-markers-value="<%= @markers.to_json %>"
              data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
              </div>




<%# <%= cl_image_tag instrument.photo.key, height: 300, width: 400, crop: :fill %>
</div>

app/views/instruments/my_instruments.html.erb
<div data-controller="show">

  <div class="grid-center">
    <div class="d-flex my_instruments">
      <h2 data-action="click->show#myRents" data-show-target="btnMyRents" class="me-3 mt-3 active">My rents</h2>
      <h2 data-action="click->show#myInstrumentsRented" data-show-target="btnmyInstrumentsRented" class="me-3 mt-3">My Instruments rented</h2>
      <h2 data-action="click->show#myInstruments" class="me-3 mt-3" data-show-target="btnMyInstruments" >My Instruments</h2>
    </div>
    <hr>
  </div>

  <div class="grid-center">
    <div data-show-target="myRents">
      <div class="grid">
        <% @rentals.each do |rental| %>
          <% instrument = Instrument.find(rental.instrument_id)  %>
          <div class="card">
            <%= cl_image_tag instrument.photo.key, height: 300, width: 400, :crop => "pad" %>
            <div class="card-infos">
              <div>
                <h2> <%= instrument.name %></h2>
                <div class="text-card">
                  <p>
                    <b><%= ((rental.end_date - rental.start_date)/(60*60*24)).to_i %> days left</b>
                    <br>
                    From : <%= rental.start_date.strftime('%a %d %b %Y') %>
                    <br>
                    Until : <%= rental.end_date.strftime('%a %d %b %Y') %>
                  </p>
                  <p><%= rental.status %></p>
                </div>
                <%= button_to "Cancel", rental, method: :delete, class:"btn-half btn-half-black btn-full-black" if policy(rental).destroy? %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>


    <div data-show-target="myInstrumentsRented" class="d-none">
      <% if @my_rentals.count > 0%>
        <div class="grid">
          <% @my_rentals.each do |rental| %>
            <% instrument = Instrument.find(rental.instrument_id)  %>
            <div class="card">
              <%= cl_image_tag instrument.photo.key, height: 300, width: 400, :crop => "pad" %>
              <div class="card-infos">
                <div>
                  <h2> <%= instrument.name %></h2>
                  <div class="text-card">
                    <p>
                      <b><%= ((rental.end_date - rental.start_date)/(60*60*24)).to_i %> days left</b>
                      <br>
                      From : <%= rental.start_date.strftime('%a %d %b %Y') %>
                      <br>
                      Until : <%= rental.end_date.strftime('%a %d %b %Y') %>
                    </p>
                    <p><%= rental.status %></p>
                  </div>

                  <% if rental.status == 'pending' %>
                  <div class="d-flex justify-content-between">
                    <%= simple_form_for(rental) do |f| %>
                      <%= f.input :status, :as => :hidden, :input_html => { :value => "approved" }%>
                      <%= f.submit "Approve", class: "btn btn-color"%>
                    <% end %>

                    <%= simple_form_for(rental) do |f| %>
                      <%= f.input :status, :as => :hidden, :input_html => { :value => "declined" }%>
                      <%= f.submit "Decline", class: "btn-semi btn-half-black"%>
                    <% end %>
                  </div>

                  <% end %>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>


    <div data-show-target="myInstruments" class="d-none">
      <% if user_signed_in? && @my_instruments.count > 0 %>
      <div class="grid">
        <% @my_instruments.each do |instrument| %>
          <%= link_to instrument_path(instrument) do %>
            <div class="card">
              <% if instrument.photo != nil %>
                <%= cl_image_tag instrument.photo.key, height: 300, width: 400, crop: :fill %>
              <% end %>
              <div class="card-infos">
                <div>
                  <h2><%= instrument.name%></h2>
                  <div class="text-card">
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse  rem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lect rem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lect rem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectrem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lect lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor</p>
                  </div><br>
                  <h2 class="card-pricing">€<%= instrument.price %></h2>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/instruments/new.html.erb
<div class="card-half">
  <h2>Create a new music instrument</h2>
  <br>
  <%= simple_form_for(@instrument) do |f| %>
    <%= f.input :name, placeholder: "Instrument name" %>
    <%= f.input :address,
      input_html: { data: { address_autocomplete_target: "address" }, class: "d-none" },
      wrapper_html: { data: { controller: "address-autocomplete",
      address_autocomplete_api_key_value: ENV['MAPBOX_API_KEY'] }, class: "mapboxgl-ctrl-geocoder" }
     %>
    <%= f.input :description, placeholder: "Description of the instrument" %>
    <%= f.input :price, placeholder: "25" %>
    <%= f.input :photo, as: :file %>
    <%= f.submit class: 'btn-large' %>
  <% end %>
</div>

app/views/instruments/show.html.erb
<div data-controller='flatpickr' data-flatpickr-dates-value="<%= @instrument.flatpickr_booked_dates_object.to_json %>">
  <div class="main-card">
    <div class="main-card-left">
      <% if @instrument.photo != nil %>
        <%= cl_image_tag @instrument.photo.key, height: 380, width: 380, crop: :pad %>
      <% end %>
    </div>
    <div class="main-card-right">
      <h1 class="main-card-text"><%= @instrument.name %></h1>
      <p class="main-card-text"> Description: <%= @instrument.description %></p><br>

      <p class="main-card-text"><em>Owner: <%= @instrument.user.username %></em></p>
      <p class="main-card-text"><em>Address: <%= @instrument.address %></em></p><br>
      <div class="main-card-text-inline">
        <h6 class="main-card-text" data-flatpickr-target="price" value='<%= @instrument.price %>'>Price : <%= @instrument.price %>€ / day &#8196</h6>
        <% if @instrument.user != current_user %>
          <h6 class="main-card-text">-&#8196<strong data-flatpickr-target="totalPrice" value='<%= @instrument.price%>' >Total price : <%= @instrument.price %>€</strong></h6>
        <% end %>
      </div><br>
      <div class="main-card-text-inline">
  <% if @instrument.user == current_user %>
        <% @instrument.rentals.all.select{|rental| rental.status == "pending"}.first(2).each do |rental| %>
        <% if rental.status == "pending" %>
          <div class="accept-refuse-box">
            <p>start date: <%= rental.start_date %> </p>
            <p class="m-0">end date: <%= rental.end_date %> </p>
            <div class="d-flex justify-content-start">
                <%= simple_form_for(rental) do |f| %>
                <%= f.input :status, :as => :hidden, :input_html => { :value => "approved" }%>
                <%= f.submit "Approve", class: "btn btn-success"%>
              <% end %>

              <%= simple_form_for(rental) do |f| %>
                <%= f.input :status, :as => :hidden, :input_html => { :value => "declined" }%>
                <%= f.submit "Decline", class: "btn btn-danger text-white ms-3"%>
              <% end %>
            </div>
          <% end %>
        </div>

        <% end %>

          <div class = "main-card-form">
            <% if policy(@instrument).edit? %>
            <%= button_to "Edit instrument", edit_instrument_path(@instrument), :method => :get, :class => "btn-half" %>
            <% end %>
            <%= button_to "Delete", @instrument, method: :delete, class:"btn-half btn-half-black" if policy(@instrument).destroy? %>
          </div>


  <% else %>
      <%= simple_form_for [@instrument, @rental],
                          html: { class: 'main-card-form'
                          } do |f| %>
        <%= f.input :start_date,
                    as: :string,
                    input_html: {
                      class: "main-card-input",
                      data: {
                        flatpickr_target: 'startDateInput',
                        action: "flatpickr#start"
        } } %>
        <%= f.input :end_date,
                    as: :string,
                    input_html: {
                      class: "main-card-input",
                      data: {
                        flatpickr_target: 'endDateInput',
                        id: 'haha'
                      }
      } %>
        <% if current_user%>
          <%= f.submit 'Book now!', class: 'btn btn-large' %>
        <% else %>
          <%= link_to new_user_session_path do %>
          <div class="haha">
            <div class="width-btn">Book now!</div>
          </div>

          <% end %>
        <% end %>
      <% end %>
  <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
  <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>

    <title>MADZIK</title>
    <%= favicon_link_tag asset_path('navbar_logo.png') %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
    <script>
    $(function() {
      $('input[name="daterange"]').daterangepicker({
        opens: 'left'
      }, function(start, end, label) {
        console.log("A new date selection was made: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
      });
    });
    </script>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
  </head>

  <body>
   <%= render 'shared/navbar'%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'shared/footer'%>
  </body>


</html>

app/views/pages/home.html.erb
<div class="grid-center">
  <%= render 'shared/title-center'%>
  <%= render render 'shared/card', instrument: @instrument%>

</div>

app/views/rentals/_form.html.erb
<%= simple_form_for [instrument, rental],
                    html: {
                      data: {
                        controller: 'flatpickr'
                      }
                    } do |f| %>
  <%= f.input :start_date,
              as: :string,
              input_html: {
                data: {
                  flatpickr_target: 'startDateInput',
} } %>
  <%= f.input :end_date,
              as: :string,
              input_html: {
                data: {
                  flatpickr_target: 'endDateInput'
                }
} %>
  <%= f.submit 'Book now!', class: 'btn btn-primary' %>
<% end %>

app/views/rentals/edit.html.erb
<%= render 'form', instrument: @instrument, rental: @rental %>

app/views/rentals/index.html.erb
<div class="grid-center">
<% if @my_rentals.count > 0%>
  <h2>My instruments rented</h2>
  <div class="grid">
    <% @my_rentals.each do |rental| %>
      <% instrument = Instrument.find(rental.instrument_id)  %>
      <div class="card">
        <%= cl_image_tag instrument.photo.key, height: 300, width: 400, :crop => "pad" %>
        <div class="card-infos">
          <div>
            <h2> <%= instrument.name %></h2>
            <div class="text-card">
              <p>
                <b><%= ((rental.end_date - rental.start_date)/(60*60*24)).to_i %> days left</b>
                <br>
                From : <%= rental.start_date.strftime('%a %d %b %Y') %>
                <br>
                Until : <%= rental.end_date.strftime('%a %d %b %Y') %>
              </p>
              <p><%= rental.status %></p>
            </div>

            <% if rental.status == 'pending' %>
            <div class="d-flex justify-content-between">
              <%= simple_form_for(rental) do |f| %>
                <%= f.input :status, :as => :hidden, :input_html => { :value => "approved" }%>
                <%= f.submit "Approve", class: "btn btn-success"%>
              <% end %>

              <%= simple_form_for(rental) do |f| %>
                <%= f.input :status, :as => :hidden, :input_html => { :value => "declined" }%>
                <%= f.submit "Decline", class: "btn btn-danger text-white"%>
              <% end %>
            </div>

            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>

<% end %>


<h2>My rents</h2>
<div class="grid">
  <% @rentals.each do |rental| %>
    <% instrument = Instrument.find(rental.instrument_id)  %>
    <div class="card">
      <%= cl_image_tag instrument.photo.key, height: 300, width: 400, :crop => "pad" %>
      <div class="card-infos">
        <div>
          <h2> <%= instrument.name %></h2>
          <div class="text-card">
            <p>
              <b><%= ((rental.end_date - rental.start_date)/(60*60*24)).to_i %> days left</b>
              <br>
              From : <%= rental.start_date.strftime('%a %d %b %Y') %>
              <br>
              Until : <%= rental.end_date.strftime('%a %d %b %Y') %>
            </p>
            <p><%= rental.status %></p>
          </div>
          <%= button_to "Cancel", rental, method: :delete, class:"btn-half btn-half-black btn-full-black" if policy(rental).destroy? %>
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>

app/views/rentals/new.html.erb
<div class="card-half">
  <%= render 'form', instrument: @instrument, rental: @rental %>
</div>

app/views/rentals/show.html.erb
<%= render 'form', instrument: @instrument, rental: @rental %>
<%= @rental.status %>

app/views/shared/_card.html.erb
<div class="card">
  <img src="https://m.media-amazon.com/images/I/813oDnJEgeL._AC_SX425_.jpg" />
  <div class="card-infos">
    <div>
      <h2>Title here</h2>
      <div class="text-card">
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse  rem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lect rem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lect rem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lectrem ipsum dolor sit amet, consectetur adipiscing elit. Sed non risus. Suspendisse lect lectus tortor, dignissim sit amet, adipiscing nec, ultricies sed, dolor</p>
      </div><br>
      <h2 class="card-pricing">€19.99</h2>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    A beautiful project ❤️
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" data-controller="navbar"
  data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "navbar_logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "New instrument", new_instrument_path , class: "btn-ghost" %>
             </li>

          <li class="nav-item active">
          <%= link_to "My personal space", my_instruments_instruments_path , class: "btn-ghost" %>
          </li>

          <li class="nav-item dropdown">
            <%= image_tag "avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%#= link_to "Action", "#", class: "dropdown-item" %>
              <%#= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_title-center.html.erb
<div class = "title-center" >
<%= form_with url: root_path, method: :get do %>
  <div class="search-form-control form-group">
    <%= text_field_tag :query,
      params[:query],
      class: "form-control string required",
      placeholder: "Find an instrument"
    %>
   <button name="button" type="submit" class="btn btn-color">
        <i class="fas fa-search"></i> Search
      </button>
  </div>
<% end %>
</div>